service: cart-service

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${opt:stage, "dev"}

environment:
  DATABASE_HOST: ${env:DATABASE_HOST}
  DATABASE_PORT: ${env:DATABASE_PORT}
  DATABASE_USERNAME: ${env:DATABASE_USERNAME}
  DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
  DATABASE_NAME: ${env:DATABASE_NAME}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"
